# Generated by Django 4.0.4 on 2022-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
