# Generated by Django 4.0.6 on 2022-08-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement_app', '0006_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
    ]
