# Generated by Django 4.0.6 on 2022-08-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement_app', '0007_remove_project_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='department',
            field=models.CharField(default='HR', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projectmanagement_app.projectmanager'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
