# Generated by Django 4.0.6 on 2023-08-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement_app', '0008_projectmanager_department_alter_project_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
    ]
